/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Currency = { 'icp' : null };
export type ItemId = bigint;
export interface Listing {
  'status' : ListingStatus,
  'itemId' : ItemId,
  'listingId' : ListingId,
  'createdAt' : Time,
  'seller' : User,
  'buyer' : [] | [User],
  'price' : PriceDetails,
}
export type ListingId = bigint;
export type ListingStatus = { 'sold' : null } |
  { 'inactive' : null } |
  { 'available' : null };
export type Price = bigint;
export interface PriceDetails { 'currencyType' : Currency, 'amount' : Price }
export type Time = bigint;
export type TransactionId = bigint;
export type User = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminUnlist' : ActorMethod<[ListingId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, PriceDetails, Array<string>],
    ListingId
  >,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[ListingId], Listing>,
  'getListingsByStatus' : ActorMethod<[ListingStatus], Array<Listing>>,
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseListing' : ActorMethod<[ListingId], TransactionId>,
  'updateListing' : ActorMethod<
    [ListingId, string, Array<string>, PriceDetails],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];