/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ListingId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Currency = IDL.Variant({ 'icp' : IDL.Null });
export const Price = IDL.Nat64;
export const PriceDetails = IDL.Record({
  'currencyType' : Currency,
  'amount' : Price,
});
export const ListingStatus = IDL.Variant({
  'sold' : IDL.Null,
  'inactive' : IDL.Null,
  'available' : IDL.Null,
});
export const ItemId = IDL.Nat;
export const Time = IDL.Int;
export const User = IDL.Principal;
export const Listing = IDL.Record({
  'status' : ListingStatus,
  'itemId' : ItemId,
  'listingId' : ListingId,
  'createdAt' : Time,
  'seller' : User,
  'buyer' : IDL.Opt(User),
  'price' : PriceDetails,
});
export const TransactionId = IDL.Nat;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminUnlist' : IDL.Func([ListingId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, PriceDetails, IDL.Vec(IDL.Text)],
      [ListingId],
      [],
    ),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([ListingId], [Listing], ['query']),
  'getListingsByStatus' : IDL.Func(
      [ListingStatus],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseListing' : IDL.Func([ListingId], [TransactionId], []),
  'updateListing' : IDL.Func(
      [ListingId, IDL.Text, IDL.Vec(IDL.Text), PriceDetails],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ListingId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Currency = IDL.Variant({ 'icp' : IDL.Null });
  const Price = IDL.Nat64;
  const PriceDetails = IDL.Record({
    'currencyType' : Currency,
    'amount' : Price,
  });
  const ListingStatus = IDL.Variant({
    'sold' : IDL.Null,
    'inactive' : IDL.Null,
    'available' : IDL.Null,
  });
  const ItemId = IDL.Nat;
  const Time = IDL.Int;
  const User = IDL.Principal;
  const Listing = IDL.Record({
    'status' : ListingStatus,
    'itemId' : ItemId,
    'listingId' : ListingId,
    'createdAt' : Time,
    'seller' : User,
    'buyer' : IDL.Opt(User),
    'price' : PriceDetails,
  });
  const TransactionId = IDL.Nat;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminUnlist' : IDL.Func([ListingId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, PriceDetails, IDL.Vec(IDL.Text)],
        [ListingId],
        [],
      ),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([ListingId], [Listing], ['query']),
    'getListingsByStatus' : IDL.Func(
        [ListingStatus],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseListing' : IDL.Func([ListingId], [TransactionId], []),
    'updateListing' : IDL.Func(
        [ListingId, IDL.Text, IDL.Vec(IDL.Text), PriceDetails],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };